parameters:
  notification_channels:
    email:
      primary: 'App\NotificationPublisher\Infrastructure\Email\SMTPSender'
      secondary: 'App\NotificationPublisher\Infrastructure\Email\WhatsappSender'
    sms:
      primary: 'App\NotificationPublisher\Infrastructure\SMS\NexmoSender'
      secondary: 'App\NotificationPublisher\Infrastructure\SMS\AwsSesSender'
    push:
      primary: 'App\NotificationPublisher\Infrastructure\Push\PushySender'
      secondary: 'App\NotificationPublisher\Infrastructure\Push\FirebaseSender'
