parameters:
  notification_channels:
    email:
      primary: 'App\NotificationPublisher\Infrastructure\Email\AwsSesSender'
      secondary: 'App\NotificationPublisher\Infrastructure\Email\SMTPSender'
    sms:
      primary: 'App\NotificationPublisher\Infrastructure\SMS\TwilioSender'
      secondary: 'App\NotificationPublisher\Infrastructure\SMS\NexmoSender'
    push:
      primary: 'App\NotificationPublisher\Infrastructure\Push\PushySender'
      secondary: 'App\NotificationPublisher\Infrastructure\Push\FirebaseSender'
