mailer:
class: sfMailer
param:
logging: %SF_LOGGING_ENABLED%
charset: %SF_CHARSET%
delivery_strategy: realtime
transport:
class: Swift_SmtpTransport
param:
host: smtp.sendgrid.net
port: 587
encryption: ~
username: apikey
api_key: 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