imports:
  - { resource: 'notifications.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\NotificationPublisher\Application\Service\NotificationManager:
        arguments:
            $notificationSenders: !tagged_iterator notification_sender
            $channelConfig: '%notification_channels%'

    App\NotificationPublisher\Application\Handler\SendNotificationHandler: ~

    App\NotificationPublisher\Command\SendNotificationCommand:
        tags: ['console.command']

    App\NotificationPublisher\Infrastructure\Email\AwsSesSender:
        tags: ['notification_sender']

    App\NotificationPublisher\Infrastructure\Email\SMTPSender:
        tags: ['notification_sender']

    App\NotificationPublisher\Infrastructure\SMS\TwilioSender:
        tags: ['notification_sender']

    App\NotificationPublisher\Infrastructure\SMS\NexmoSender:
        tags: ['notification_sender']

    App\NotificationPublisher\Infrastructure\Push\PushySender:
        tags: ['notification_sender']

    App\NotificationPublisher\Infrastructure\Push\FirebaseSender:
        tags: ['notification_sender']
